# Generated by Django 5.2.13 on 2026-07-20 20:09

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_init_v2"),
        ("authentication", "0026_alter_characterownership_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="approver_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user that manage the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="requesting_user",
            field=models.ForeignKey(
                help_text="The requesting user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="authentication.user",
            ),
        ),
    ]
