# Generated by Django 5.2.13 on 2026-09-20 14:04

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_request_approver_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("corporation_access", "Can access own corporation assets"),
                    ("admin_access", "Can access all assets."),
                    ("manage_corporation", "Can add corporation assets"),
                    ("manage_requests", "Can manage requests"),
                ),
                "verbose_name": "AA-Assets",
                "verbose_name_plural": "AA-Assets",
            },
        ),
    ]
