# Generated by Django 4.2.11 on 2025-05-01 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0010_alter_eveindustryactivityduration_eve_type_and_more"),
        ("assets", "0002_alter_request_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="order",
        ),
        migrations.AddField(
            model_name="request",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name of the Requestor", max_length=100, null=True
            ),
        ),
        migrations.CreateModel(
            name="RequestAssets",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the Asset", max_length=100),
                ),
                (
                    "asset_pk",
                    models.PositiveBigIntegerField(
                        help_text="The asset this request belongs to"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantity of assets"
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        help_text="The asset type this request belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        help_text="The request this asset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assets.request",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
