# Generated by Django 4.2.23 on 2025-07-10 07:45

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_remove_request_order_request_name_requestassets"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("corporation_access", "Can access own corporation assets"),
                    ("admin_access", "Can access all assets."),
                    ("manage_corporation", "Can add corporation assets"),
                    ("manage_requests", "Can manage requests"),
                ),
            },
        ),
    ]
