# Generated by Django 4.2.29 on 2026-03-09 09:30

# Django
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("assets", "0004_alter_general_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assets",
            name="eve_type",
            field=models.ForeignKey(
                help_text="asset type",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="eve_solar_system",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="eve_sde.solarsystem",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="eve_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="requestassets",
            name="eve_type",
            field=models.ForeignKey(
                help_text="The asset type this request belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.CreateModel(
            name="EveEntity",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("alliance", "Alliance"),
                            ("corporation", "Corporation"),
                            ("character", "Character"),
                        ],
                        max_length=32,
                        verbose_name="Category",
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "alliance",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alli",
                        to="assets.eveentity",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corp",
                        to="assets.eveentity",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
