# Generated by Django 4.2.28 on 2026-03-03 17:01

# Django
from django.db import migrations


def on_migrate(apps, schema_editor):
    try:
        OldEveEntity = apps.get_model("eveuniverse", "EveEntity")
    except LookupError:
        print("EVE Universe Model not found skipping migration.")
        return
    EveEntity = apps.get_model("assets", "EveEntity")
    batch_size = 1000
    old_entities = OldEveEntity.objects.exclude(
        id__in=EveEntity.objects.values_list("id", flat=True)
    ).only("id", "name", "category")
    migrated = 0
    bulk_list = []

    for old_entity in old_entities.iterator(chunk_size=batch_size):
        bulk_list.append(
            EveEntity(
                id=old_entity.id,
                name=old_entity.name,
                category=old_entity.category,
            )
        )

        if len(bulk_list) >= batch_size:
            created = EveEntity.objects.bulk_create(
                bulk_list, ignore_conflicts=True, batch_size=batch_size
            )
            migrated += len(created)
            bulk_list = []

    if bulk_list:
        created = EveEntity.objects.bulk_create(
            bulk_list, ignore_conflicts=True, batch_size=batch_size
        )
        migrated += len(created)


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0014_dogmaeffect_description_de_and_more"),
        ("assets", "0005_alter_assets_eve_type_and_more"),
    ]

    operations = [
        migrations.RunPython(on_migrate),
    ]
