# Generated by Django 4.2.29 on 2026-03-09 09:32

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_migrate_eveentity_alter_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="corporation this station or structure belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="assets.eveentity",
            ),
        ),
    ]
